version: 0.2

run-as: root

proxy:
  upload-artifacts: no
  logs: yes

batch:
  fast-fail: false
        
phases:
  install:
    run-as: root
    on-failure: ABORT
    runtime-versions:
      nodejs: 12
    commands:
      - npm i
  post_build:
    run-as: root
    on-failure: ABORT
    commands:
      - npm start &
      - npx cypress run