name: Cypress Tests

on: [push]

jobs:
  ui-chrome-tests:
    runs-on: ubuntu-latest
    container: cypress/browsers:node12.18.3-chrome87-ff82
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2, 3]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # - name: 'UI Tests - Chrome'
      #   uses: cypress-io/github-action@v4.2.0
      #   with:
      #     install: false
      #     start: npm start
      #     wait-on: 'http://localhost:8085'
      #     wait-on-timeout: 120
      #     browser: chrome
      #     record: true
      #     group: 'UI - Chrome'
      #     spec: $(npx split-files 'cypress/e2e' '.*\.cy\.js$' 5 2)
      - name: install
        run: npm i
      - name: Echo stuff
      run: |
          echo 'the info is $(npx split-files 'cypress/e2e' '.*\.cy\.js$' 5 2)'
          echo '${{ matrix.containers }}'
          echo 'the info is $(npx split-files 'cypress/e2e' '.*\.cy\.js$' 5 2) ${{ matrix.containers }}'       
        
