name: Cypress Tests

on: [push]

jobs:
  ui-chrome-tests:
    runs-on: ubuntu-latest
    container: cypress/browsers:node12.18.3-chrome87-ff82
    strategy:
      fail-fast: false
      matrix:
        containers: [0, 1, 2]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: GetSpecs
        run: echo "::set-output name=action_fruit::strawberry"
      - name: install
        run: npm i
      - name: test
        run: "npx cypress run --spec=$(npx split-files 'cypress/e2e' '.*\.cy\.js$' 3 ${{ matrix.containers }})" # note that for this step to work, your cypress installation would need to 
        
